package hello.dao;

import hello.dataObject.ItemInfo;
import org.springframework.stereotype.Component;

@Component
public interface ItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Jan 07 16:25:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Jan 07 16:25:28 CST 2020
     */
    int insert(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Jan 07 16:25:28 CST 2020
     */
    int insertSelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Jan 07 16:25:28 CST 2020
     */
    ItemInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Jan 07 16:25:28 CST 2020
     */
    int updateByPrimaryKeySelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Jan 07 16:25:28 CST 2020
     */
    int updateByPrimaryKey(ItemInfo record);
}