package hello.dao;

import hello.dataObject.ItemInfo;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jan 08 11:31:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jan 08 11:31:52 CST 2020
     */
    int insert(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jan 08 11:31:52 CST 2020
     */
    int insertSelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jan 08 11:31:52 CST 2020
     */
    ItemInfo selectByPrimaryKey(Integer id);
    List<ItemInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jan 08 11:31:52 CST 2020
     */
    int updateByPrimaryKeySelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jan 08 11:31:52 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jan 08 11:31:52 CST 2020
     */
    int updateByPrimaryKey(ItemInfo record);
}